engines:
  fixme:
    enabled: true
  eslint:
    enabled: true
  nodesecurity:
    enabled: false
  markdownlint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
exclude_paths: ['node_modules', '.idea']
